from .keeper_analyser import keeper
from .defender_analyser import defender
from .fullback_analyser import fullback
from .wingback_analyser import wingback
from .defensive_midfielder_analyser import defensive_midfielder
from .central_midfielder_analyser import central_midfielder
from .attacking_midfielder_analyser import attacking_midfielder
from .winger_analyser import winger
from .striker_analyser import striker